{
 "title": "Statistic By Xinyu‘s Routine",
 "time": { "from": "2024-12-19T14:35:11.881Z", "to": "2024-12-19T14:37:09.416Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster_name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{cluster_name=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{cluster_name=\"$cluster\"},nodename)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "APIServer-Overview",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "cluster",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=\"apiserver\"}) by(cluster_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rpc fail rate - $cluster",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", code=~\"3.*|4.*|5.*\", cluster_name=\"$cluster\",resource!=\"\"}[1m])) by(resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "rpc rate - $cluster",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{job=\"apiserver\", code=~\"2.*\", cluster_name=\"$cluster\",resource!=\"\"}[1m])) by(resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETCD-Overview",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "repeat": "cluster",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(etcd_server_has_leader) by (cluster_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "etcd_disk_wal_fsync_duration_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{}[1m])) by (cluster_name, instance, le))",
       "legendFormat": "{{cluster_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "etcd_disk_backend_commit_duration_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{}[1m])) by (cluster_name, instance, le))",
       "legendFormat": "{{cluster_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "grpc-rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[1m])) by(cluster_name,grpc_service) ",
       "legendFormat": "{{cluster_name}}/{{grpc_service}}"
      }
     ]
    },
    {
     "title": "grpc-fail-rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by(cluster_name,grpc_service) ",
       "legendFormat": "{{cluster_name}}/{{grpc_service}}"
      }
     ]
    },
    {
     "title": "DB-Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "etcd_mvcc_db_total_size_in_bytes{}",
       "legendFormat": "{{cluster_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "etcd-leader-changes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "changes(etcd_server_leader_changes_seen_total{}[1d])",
       "legendFormat": "{{cluster_name}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Prometheus Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"insight-agent-kube-prometh-prometheus\",cluster_name!=\"\"}",
       "legendFormat": "{{cluster_name}}/{{container}}"
      }
     ]
    },
    {
     "title": "Prometheus Samples Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{cluster_name!=\"\",type=\"float\"}[1m])",
       "legendFormat": "{{cluster_name}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Kafka Bandwidth Avg",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka-0\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka-0\"}[24h]) \n)/24/3600",
       "legendFormat": "efk-kafka-0"
      },
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka-1\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka-1\"}[24h]) \n)/24/3600",
       "legendFormat": "efk-kafka-1"
      },
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka-2\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka-2\"}[24h]) \n)/24/3600",
       "legendFormat": "efk-kafka-2"
      }
     ]
    },
    {
     "title": "Kafka Bandwidth",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka.*\"}[1m]))",
       "legendFormat": "efk-kafka-receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"efk-kafka.*\"}[1m]))",
       "legendFormat": "efk-kafka-transmit"
      }
     ]
    },
    {
     "title": "Prometheus Bandwidth Avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"dao-system\", pod=~\"prometheus-dx-insight-prometheus-0\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"dao-system\", pod=~\"prometheus-dx-insight-prometheus-0\"}[24h]) \n)/24/3600",
       "legendFormat": "prometheus-dx-insight-prometheus-0"
      },
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"dao-system\", pod=~\"prometheus-dx-insight-prometheus-1\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"dao-system\", pod=~\"prometheus-dx-insight-prometheus-1\"}[24h]) \n)/24/3600",
       "legendFormat": "prometheus-dx-insight-prometheus-1"
      }
     ]
    },
    {
     "title": "Logstash Bandwidth",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"logstash.*\"}[1m]))",
       "legendFormat": "logstash-receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"logstash.*\"}[1m])) ",
       "legendFormat": "logstash-transmit"
      }
     ]
    },
    {
     "title": "ES Bandwidth Avg",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master-0\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master-0\"}[24h]) \n)/24/3600",
       "legendFormat": "elasticsearch-master-0"
      },
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master-1\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master-1\"}[24h]) \n)/24/3600",
       "legendFormat": "elasticsearch-master-1"
      },
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master-2\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master-2\"}[24h]) \n)/24/3600",
       "legendFormat": "elasticsearch-master-2"
      }
     ]
    },
    {
     "title": "Prometheus Bandwidth",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"dao-system\", pod=~\"prometheus-dx-insight-prometheus.*\"}[1m]))/2",
       "legendFormat": "prometheus-receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"dao-system\", pod=~\"prometheus-dx-insight-prometheus.*\"}[1m]))/2",
       "legendFormat": "prometheus-transmit"
      }
     ]
    },
    {
     "title": "Skywalking Bandwidth Avg",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-555664b449-42b9s\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-555664b449-42b9s\"}[24h]) \n)/24/3600",
       "legendFormat": "dmp-skywalking-oap-m-555664b449-42b9s"
      },
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-555664b449-l7hgx\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-555664b449-l7hgx\"}[24h]) \n)/24/3600",
       "legendFormat": "dmp-skywalking-oap-m-555664b449-l7hgx"
      },
      {
       "expr": "sum(\n    increase(container_network_receive_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-555664b449-zdbp6\"}[24h]) +\n    increase(container_network_transmit_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-555664b449-zdbp6\"}[24h]) \n)/24/3600",
       "legendFormat": "dmp-skywalking-oap-m-555664b449-zdbp6"
      }
     ]
    },
    {
     "title": "Skywalking Bandwidth",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-.*\"}[1m])) ",
       "legendFormat": "dmp-skywalking-oap-m-receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"dmp-system\", pod=~\"dmp-skywalking-oap-m-.*\"}[1m]))",
       "legendFormat": "dmp-skywalking-oap-m-transmit"
      }
     ]
    },
    {
     "title": "ES Bandwidth",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master.*\"}[1m])) ",
       "legendFormat": "elasticsearch-master-receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"efk-system\", pod=~\"elasticsearch-master.*\"}[1m]))",
       "legendFormat": "elasticsearch-master-transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "application-pod-OOMKilled-terminated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "count_over_time(kube_pod_container_status_terminated_reason{namespace!~\".*system$|.*hwameistor$|argocd\",reason=~\"OOMKilled\"}[1m]) >0",
       "legendFormat": "{{namespace}}/{{pod}}-{{reason}}"
      }
     ]
    },
    {
     "title": "system-pod-OOMKilled-terminated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "count_over_time(kube_pod_container_status_terminated_reason{namespace=~\".*system$|.*hwameistor$|argocd\",reason=~\"OOMKilled\"}[1m]) >0",
       "legendFormat": "{{namespace}}/{{pod}}-{{reason}}"
      }
     ]
    },
    {
     "title": "applications-pod-restarts > 3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{namespace!~'argocd|virtnest-systemstem|kant-system|dowl-system|gmagpie-systemkcollie-system|kcoral-system|kangaroo-system| spidernet-system|mspider-system|kairship-system| amamba-system| skoala-system|ipavo-system|insight-system| ghippo-system|mcamel-system|kpanda-system|metallb-system|istio-system|kubean-system|kube-system|hwameistor'}[2m]) * 120 > 3",
       "legendFormat": "{{namespace}}/{{pod}}-{{reason}}"
      }
     ]
    },
    {
     "title": "system-pod-restarts > 0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{namespace=~'argocd|virtnest-systemstem|kant-system|dowl-system|gmagpie-systemkcollie-system|kcoral-system|kangaroo-system| spidernet-system|mspider-system|kairship-system| amamba-system| skoala-system|ipavo-system|insight-system| ghippo-system|mcamel-system|kpanda-system|metallb-system|istio-system|kubean-system|kube-system|hwameistor'}[2m]) * 120 > 0",
       "legendFormat": "{{namespace}}/{{pod}}-{{reason}}"
      }
     ]
    },
    {
     "title": "node-fs-usage-available < 20%",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{mountpoint=\"/var/lib/containers\"}/node_filesystem_size_bytes{mountpoint=\"/var/lib/containers\"}*100<20",
       "legendFormat": "{{cluser_name}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "application_pod_cpu_usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace!~\".*system$|.*hwameistor$\",container!=\"\"}) by (namespace, pod))",
       "legendFormat": "{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "system_pod_cpu_usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\".*system$|.*hwameistor$\",container!=\"\"}) by (namespace, pod))",
       "legendFormat": "{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "application_pod_memory_usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum(container_memory_working_set_bytes{namespace!~\".*system$|.*hwameistor$\", container!=\"\", image!=\"\"}) by (namespace, pod))",
       "legendFormat": "{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "system_pod_memory_usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum(container_memory_working_set_bytes{namespace=~\".*system$|.*hwameistor$\", container!=\"\", image!=\"\"}) by (namespace, pod))",
       "legendFormat": "{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "container_cpu_cfs_throttled/periods_ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(topk(10,sum(increase(container_cpu_cfs_throttled_periods_total{container!=\"\"}[5m])) by (container, pod, namespace,cluster_name)/sum(increase(container_cpu_cfs_periods_total[5m])) by (container, pod, namespace,cluster_name)))",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod in Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pod CPU Usage - Host - $node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=\"$node\",container!=\"\"}) by (namespace, pod))",
       "legendFormat": "{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Memory Utilization - Host - $node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum(container_memory_working_set_bytes{node=\"$node\", container!=\"\", image!=\"\"}) by (namespace, pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod CPU limits/requests-ratio - $node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(15,(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{node=\"$node\", resource=\"cpu\"}\n  ) /\n  sum by (namespace, pod) (\n    kube_pod_container_resource_requests{node=\"$node\", resource=\"cpu\"}\n  )\n) > 1)\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Mem limits/requests-ratio - $node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{node=\"$node\", resource=\"memory\"}\n  ) /\n  sum by (namespace, pod) (\n    kube_pod_container_resource_requests{node=\"$node\", resource=\"memory\"}\n  )\n) > 1)\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU - $node - $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|steal\", instance=\"$instance\"}[30s])))/ ignoring(cpu) group_left  count without (cpu, mode) (node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"$instance\"}))*100",
       "legendFormat": "{{cpu}}"
      }
     ]
    },
    {
     "title": "Node  Load - $node - $instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "1m load average"
      },
      {
       "expr": "node_load5{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "5m load average"
      },
      {
       "expr": "node_load15{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "15m load average"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"$instance\", mode=\"idle\"})",
       "legendFormat": "logical cores"
      }
     ]
    },
    {
     "title": "Node Memory - $node - $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"} -  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\"}-  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\"}-  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\"})",
       "legendFormat": "memory used"
      },
      {
       "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "memory buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "memory cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\"}",
       "legendFormat": "memory free"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Nacos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Zookeeper Avg Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(avg_latency[5m])>20",
       "legendFormat": "{{ application}}-{{instance}}-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$cluster-cpu-usage/request-percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pod_cpu_usage{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "dce5-active01-memory-usage/request-percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(pod_memory_usage{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "dce5-active01-memory-usage/request-percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(pod_memory_usage{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}[1m]) by(namespace) / sum(pod_memory_requests{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}) by(namespace)* 100 ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "dce5-active01-cpu-usage/request-percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(pod_cpu_usage{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}[1m]) by(namespace) / sum(pod_cpu_requests{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}) by(namespace)* 100 ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "dce5-active01-cpu-usage/limit-percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(pod_cpu_usage{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}[1m]) by(namespace) / sum(pod_cpu_limits{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}) by(namespace)* 100 ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "dce5-active01-memory-usage/limit-percent",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(pod_memory_usage{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}[1m]) by(namespace) / sum(pod_memory_limits{cluster_name=\"$cluster\",namespace!~\"cert-manager|default|hwameistor|.*system|istio.*\"}) by(namespace)* 100 ",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace Resource Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "dce5-active01-statistic",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(pod_cpu_usage{cluster_name=\"dce5-active01\",namespace=~\".*prd.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_cpu_requests{cluster_name=\"dce5-active01\",namespace=~\".*prd.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_cpu_limits{cluster_name=\"dce5-active01\",namespace=~\".*prd.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_usage{cluster_name=\"dce5-active01\",namespace=~\".*prd.*\"}[1m]) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_requests{cluster_name=\"dce5-active01\",namespace=~\".*prd.*\"}) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_limits{cluster_name=\"dce5-active01\",namespace=~\".*prd.*\"}) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "dce5-uat-statistic",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum(pod_cpu_usage{cluster_name=\"dce5-uat\",namespace=~\".*uat.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_cpu_requests{cluster_name=\"dce5-uat\",namespace=~\".*uat.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_cpu_limits{cluster_name=\"dce5-uat\",namespace=~\".*uat.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_usage{cluster_name=\"dce5-uat\",namespace=~\".*uat.*\"}[1m]) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_requests{cluster_name=\"dce5-uat\",namespace=~\".*uat.*\"}) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_limits{cluster_name=\"dce5-uat\",namespace=~\".*uat.*\"}) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "dce5-sit-statistic",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum(pod_cpu_usage{cluster_name=\"dce5-sit\",namespace=~\".*sit.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_cpu_requests{cluster_name=\"dce5-sit\",namespace=~\".*sit.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_cpu_limits{cluster_name=\"dce5-sit\",namespace=~\".*sit.*\"}[1m]) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_usage{cluster_name=\"dce5-sit\",namespace=~\".*sit.*\"}[1m]) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_requests{cluster_name=\"dce5-sit\",namespace=~\".*sit.*\"}) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(pod_memory_limits{cluster_name=\"dce5-sit\",namespace=~\".*sit.*\"}) by(namespace)/1024/1024/1024",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Resource Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Number in DaoCloud",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{cluster_name!=\"\"}) by(cluster_name)",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "system_pod_memory_usage_percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg_over_time( pod_memory_usage{namespace=~\"baize-system|argocd|virtnest-systemstem|kant-system|dowl-system|gmagpie-systemkcollie-system|kcoral-system|kangaroo-system|spidernet-system|mspider-system|kairship-system|amamba-system|skoala-system|ipavo-system|insight-system|ghippo-system|mcamel-system|kpanda-system|metallb-system|istio-system|kubean-system|kube-system|hwameistor\"}[10m] ) / avg_over_time( pod_memory_limits{namespace=~\"baize-system|argocd|virtnest-systemstem|kant-system|dowl-system|gmagpie-systemkcollie-system|kcoral-system|kangaroo-system|spidernet-system|mspider-system|kairship-system|amamba-system|skoala-system|ipavo-system|insight-system|ghippo-system|mcamel-system|kpanda-system|metallb-system|istio-system|kubean-system|kube-system|hwameistor\"}[10m] ) * 100  > 95",
       "legendFormat": "{{cluster_name}}/{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "application_pod_memory_usage_percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg_over_time( pod_memory_usage{namespace!~\"baize-system|argocd|virtnest-systemstem|kant-system|dowl-system|gmagpie-systemkcollie-system|kcoral-system|kangaroo-system|spidernet-system|mspider-system|kairship-system|amamba-system|skoala-system|ipavo-system|insight-system|ghippo-system|mcamel-system|kpanda-system|metallb-system|istio-system|kubean-system|kube-system|hwameistor\"}[10m] ) / avg_over_time( pod_memory_limits{namespace!~\"baize-system|argocd|virtnest-systemstem|kant-system|dowl-system|gmagpie-systemkcollie-system|kcoral-system|kangaroo-system|spidernet-system|mspider-system|kairship-system|amamba-system|skoala-system|ipavo-system|insight-system|ghippo-system|mcamel-system|kpanda-system|metallb-system|istio-system|kubean-system|kube-system|hwameistor\"}[10m] ) * 100  > 95",
       "legendFormat": "{{cluster_name}}/{{namespace}}/{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod QoS Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cluster/QoS",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_qos_class{cluster_name=\"$cluster\", qos_class=\"Guaranteed\"} == 1) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_pod_status_qos_class{cluster_name=\"$cluster\", qos_class=\"Burstable\"} == 1) by(namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_pod_status_qos_class{cluster_name=\"$cluster\", qos_class=\"BestEffort\"} == 1) by(namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "$cluster/$namespace/QoS",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_qos_class{cluster_name=\"$cluster\",namespace=\"$namespace\", qos_class=\"Guaranteed\"} == 1) by(namespace,pod)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_pod_status_qos_class{cluster_name=\"$cluster\", namespace=\"$namespace\", qos_class=\"Burstable\"} == 1) by(namespace,pod)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(kube_pod_status_qos_class{cluster_name=\"$cluster\", namespace=\"$namespace\", qos_class=\"BestEffort\"} == 1) by(namespace,pod)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Over Allocation Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cluster/over-allocated-rate-by-namesapce",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by (namespace)(kube_pod_container_resource_limits{resource=\"cpu\", cluster_name=\"$cluster\"}) /\nsum by (namespace)(kube_pod_container_resource_requests{resource=\"cpu\", cluster_name=\"$cluster\"}) ",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum by (namespace)(kube_pod_container_resource_limits{resource=\"memory\", cluster_name=\"$cluster\"}) /\nsum by (namespace)(kube_pod_container_resource_requests{resource=\"memory\", cluster_name=\"$cluster\"}) ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "$cluster/over-allocated-rate-by-node",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits{resource=\"cpu\", cluster_name=\"$cluster\"}) /\nsum by (node)(kube_pod_container_resource_requests{resource=\"cpu\", cluster_name=\"$cluster\"}) ",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits{resource=\"memory\", cluster_name=\"$cluster\"}) /\nsum by (node)(kube_pod_container_resource_requests{resource=\"memory\", cluster_name=\"$cluster\"}) ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "application-pod-cpu-limits/requests-ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(15,(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{namespace!~\".*system$|.*hwameistor$\", resource=\"cpu\"}\n  ) /\n  sum by (namespace, pod) (\n    kube_pod_container_resource_requests{namespace!~\".*system$|.*hwameistor$\", resource=\"cpu\"}\n  )\n) > 1)\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "$cluster/$namespace/over-allocated-rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum by (namespace, pod)(kube_pod_container_resource_limits{resource=\"cpu\", cluster_name=\"$cluster\",namespace=\"$namespace\"}) /\nsum by (namespace, pod)(kube_pod_container_resource_requests{resource=\"cpu\", cluster_name=\"$cluster\",namespace=\"$namespace\"}) ",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum by (namespace,pod)(kube_pod_container_resource_limits{resource=\"memory\", cluster_name=\"$cluster\",namespace=\"$namespace\"}) /\nsum by (namespace,pod)(kube_pod_container_resource_requests{resource=\"memory\", cluster_name=\"$cluster\",namespace=\"$namespace\"}) ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "application-pod-memory-limits/requests-ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{namespace!~\".*system$|.*hwameistor$\", resource=\"memory\"}\n  ) /\n  sum by (namespace, pod) (\n    kube_pod_container_resource_requests{namespace!~\".*system$|.*hwameistor$\", resource=\"memory\"}\n  )\n) > 1)\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "system-pod-cpu-limits/requests-ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(100,(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{namespace=~\".*system$|.*hwameistor$\", resource=\"cpu\"}\n  ) /\n  sum by (namespace, pod) (\n    kube_pod_container_resource_requests{namespace=~\".*system$|.*hwameistor$\", resource=\"cpu\"}\n  )\n) > 1)\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "system-pod-memory-limits/requests-ratio",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(50,(\n  sum by (namespace, pod) (\n    kube_pod_container_resource_limits{namespace=~\".*system$|.*hwameistor$\", resource=\"memory\"}\n  ) /\n  sum by (namespace, pod) (\n    kube_pod_container_resource_requests{namespace=~\".*system$|.*hwameistor$\", resource=\"memory\"}\n  )\n) > 1)\n",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}